### PR TITLE
Added main GitHub action file

### PR DESCRIPTION
**Pull request by roeeyn**
Add automatic linting to new PRs. Linting is executed by `pylint`

### CODE REVIEW

**Comment by roeeyn** [comment]
Closes #42

**Comment by roeeyn** [comment]
Maybe it's missing to add the flag for the `.pylintrc` file, so it doesn't look for all the issues. But I will wait for comments

**Comment by gleitz** [comment]
Thanks for the PR. Is it possible to report the linting failures? I'm interested to know what is currently not passing the lint checks. 
We may also want to provide a script that does all the types of linting we require, sort of like `npm run lint`, so it's easy for developers to run

**Comment by roeeyn** [comment]
The linting failures can be seen in the repo actions tab. Would you be interested in receiving those failures as a message? And pylint was the first step, but if you wish I could also add node linting as well in this PR

**Comment by gleitz** [comment]
Got it. When I go to https://github.com/MLH-Fellowship/howdoi/pull/43/checks?check_run_id=805771506 I see quite a few errors. We may need to manually tell the linter to use the `.pylintrc` file for the repo.

**Pull request closed without merging**
